export type Franchise = {
  slug: string;
  name: string;
  category: string;
  description: string;
  investmentMin: number;
  investmentMax: number;
  franchiseFee: number;
  royaltyPct: number;
  adFundPct: number;
  avgRevenue: number | null;
  unitCount: number;
  unitsOpened: number;
  unitsClosed: number;
  yearFounded: number;
  headquarters: string;
  tags: string[];
  website: string;
};

export const categories = [
  "Food & Beverage",
  "Health & Fitness",
  "Home Services",
  "Education",
  "Pet Services",
  "B2B Services",
  "Personal Care",
  "Automotive",
  "Senior Care",
  "Cleaning & Maintenance",
  "Real Estate",
  "Retail",
] as const;

export const franchises: Franchise[] = [
  // ─── Food & Beverage ─────────────────────────────────────────
  {
    slug: "mcdonalds",
    name: "McDonald's",
    category: "Food & Beverage",
    description:
      "The world's largest quick-service restaurant chain, serving billions annually across 40,000+ locations. Known for operational consistency, massive brand recognition, and a proven real estate-driven business model.",
    investmentMin: 1_008_000,
    investmentMax: 2_214_000,
    franchiseFee: 45_000,
    royaltyPct: 4.0,
    adFundPct: 4.0,
    avgRevenue: 3_700_000,
    unitCount: 40_275,
    unitsOpened: 805,
    unitsClosed: 312,
    yearFounded: 1955,
    headquarters: "Chicago, IL",
    tags: ["multi-unit", "financing-available"],
    website: "https://www.mcdonalds.com/us/en-us/about-us/franchising.html",
  },
  {
    slug: "chick-fil-a",
    name: "Chick-fil-A",
    category: "Food & Beverage",
    description:
      "Premium chicken quick-service restaurant with industry-leading per-unit revenue. Unique operator model with extremely low franchise fee but highly selective admission process. Closed on Sundays by company policy.",
    investmentMin: 342_990,
    investmentMax: 2_431_600,
    franchiseFee: 10_000,
    royaltyPct: 15.0,
    adFundPct: 0.0,
    avgRevenue: 8_700_000,
    unitCount: 3_059,
    unitsOpened: 148,
    unitsClosed: 12,
    yearFounded: 1967,
    headquarters: "Atlanta, GA",
    tags: ["owner-operator"],
    website: "https://www.chick-fil-a.com/franchising",
  },
  {
    slug: "taco-bell",
    name: "Taco Bell",
    category: "Food & Beverage",
    description:
      "Mexican-inspired quick-service giant and Yum! Brands subsidiary with strong late-night and value positioning. Known for constant menu innovation, a loyal fanbase, and scalable restaurant operations.",
    investmentMin: 575_600,
    investmentMax: 3_370_100,
    franchiseFee: 45_000,
    royaltyPct: 5.5,
    adFundPct: 4.25,
    avgRevenue: 2_100_000,
    unitCount: 8_791,
    unitsOpened: 289,
    unitsClosed: 142,
    yearFounded: 1962,
    headquarters: "Irvine, CA",
    tags: ["multi-unit", "financing-available"],
    website: "https://www.tacobell.com/franchise",
  },
  {
    slug: "dunkin",
    name: "Dunkin'",
    category: "Food & Beverage",
    description:
      "Iconic coffee and baked goods brand with massive East Coast presence expanding nationally. Streamlined menu and strong morning daypart drive consistent traffic. Inspire Brands subsidiary since 2020.",
    investmentMin: 526_900,
    investmentMax: 1_809_500,
    franchiseFee: 40_000,
    royaltyPct: 5.9,
    adFundPct: 5.0,
    avgRevenue: 1_450_000,
    unitCount: 13_400,
    unitsOpened: 342,
    unitsClosed: 275,
    yearFounded: 1950,
    headquarters: "Canton, MA",
    tags: ["multi-unit", "financing-available"],
    website: "https://www.dunkinfranchising.com",
  },
  {
    slug: "subway",
    name: "Subway",
    category: "Food & Beverage",
    description:
      "World's largest restaurant chain by location count, specializing in made-to-order sandwiches and salads. Low startup cost relative to peers makes it accessible for first-time franchisees. Undergoing brand refresh and menu overhaul.",
    investmentMin: 229_050,
    investmentMax: 526_400,
    franchiseFee: 15_000,
    royaltyPct: 8.0,
    adFundPct: 4.5,
    avgRevenue: 490_000,
    unitCount: 36_900,
    unitsOpened: 198,
    unitsClosed: 1_420,
    yearFounded: 1965,
    headquarters: "Shelton, CT",
    tags: ["financing-available", "owner-operator"],
    website: "https://www.subway.com/en-US/OwnAFranchise",
  },
  {
    slug: "wingstop",
    name: "Wingstop",
    category: "Food & Beverage",
    description:
      "Fast-growing wing-focused chain with a delivery-first, small-footprint model that drives strong unit economics. Digital orders exceed 60% of sales, keeping labor costs manageable. One of the hottest growth stories in QSR.",
    investmentMin: 389_500,
    investmentMax: 889_500,
    franchiseFee: 20_000,
    royaltyPct: 6.0,
    adFundPct: 4.0,
    avgRevenue: 1_800_000,
    unitCount: 2_210,
    unitsOpened: 278,
    unitsClosed: 34,
    yearFounded: 1994,
    headquarters: "Dallas, TX",
    tags: ["multi-unit", "semi-absentee", "financing-available"],
    website: "https://www.wingstop.com/own-a-wingstop",
  },
  {
    slug: "jersey-mikes",
    name: "Jersey Mike's",
    category: "Food & Beverage",
    description:
      "Premium sub sandwich franchise known for fresh-sliced meats and a strong community-oriented culture. Rapid unit growth and above-average AUV for the sandwich segment. Strong franchisee satisfaction scores.",
    investmentMin: 235_000,
    investmentMax: 765_500,
    franchiseFee: 18_500,
    royaltyPct: 6.5,
    adFundPct: 3.0,
    avgRevenue: 1_250_000,
    unitCount: 2_800,
    unitsOpened: 312,
    unitsClosed: 42,
    yearFounded: 1956,
    headquarters: "Manasquan, NJ",
    tags: ["multi-unit", "financing-available", "owner-operator"],
    website: "https://www.jerseymikes.com/franchise",
  },
  {
    slug: "tropical-smoothie-cafe",
    name: "Tropical Smoothie Cafe",
    category: "Food & Beverage",
    description:
      "Health-forward fast-casual brand serving smoothies, wraps, and flatbreads. Appeals to the growing health-conscious consumer segment with strong multi-unit operator base. Consistent same-store sales growth.",
    investmentMin: 277_000,
    investmentMax: 584_000,
    franchiseFee: 30_000,
    royaltyPct: 6.0,
    adFundPct: 3.0,
    avgRevenue: 1_100_000,
    unitCount: 1_400,
    unitsOpened: 175,
    unitsClosed: 22,
    yearFounded: 1997,
    headquarters: "Atlanta, GA",
    tags: ["multi-unit", "financing-available"],
    website: "https://www.tropicalsmoothiefranchise.com",
  },
  {
    slug: "7-eleven",
    name: "7-Eleven",
    category: "Food & Beverage",
    description:
      "The world's largest convenience store chain with unmatched brand recognition and 24/7 operations. Offers a unique turnkey franchise model where the company provides the store and inventory. Strong emphasis on fresh food and private-label products.",
    investmentMin: 56_600,
    investmentMax: 1_635_200,
    franchiseFee: 25_000,
    royaltyPct: 0.0,
    adFundPct: 0.0,
    avgRevenue: 1_600_000,
    unitCount: 13_000,
    unitsOpened: 210,
    unitsClosed: 380,
    yearFounded: 1927,
    headquarters: "Dallas, TX",
    tags: ["owner-operator", "financing-available"],
    website: "https://franchise.7-eleven.com",
  },

  // ─── Health & Fitness ────────────────────────────────────────
  {
    slug: "anytime-fitness",
    name: "Anytime Fitness",
    category: "Health & Fitness",
    description:
      "24/7 access gym franchise with the largest global gym footprint. Low-staffing model with key-fob entry system drives strong margins. Appeals to convenience-focused members who want to work out on their own schedule.",
    investmentMin: 378_000,
    investmentMax: 783_000,
    franchiseFee: 42_500,
    royaltyPct: 5.0,
    adFundPct: 2.0,
    avgRevenue: 650_000,
    unitCount: 5_100,
    unitsOpened: 165,
    unitsClosed: 88,
    yearFounded: 2002,
    headquarters: "Woodbury, MN",
    tags: ["semi-absentee", "multi-unit", "veteran-discount", "financing-available"],
    website: "https://www.anytimefitness.com/franchise",
  },
  {
    slug: "planet-fitness",
    name: "Planet Fitness",
    category: "Health & Fitness",
    description:
      "Budget gym chain targeting casual exercisers with its 'Judgement Free Zone' branding. Extremely high member-to-staff ratios and low price point create compelling unit economics. Publicly traded with strong multi-unit operator base.",
    investmentMin: 1_600_000,
    investmentMax: 4_900_000,
    franchiseFee: 20_000,
    royaltyPct: 7.0,
    adFundPct: 7.0,
    avgRevenue: 2_200_000,
    unitCount: 2_575,
    unitsOpened: 142,
    unitsClosed: 18,
    yearFounded: 1992,
    headquarters: "Hampton, NH",
    tags: ["multi-unit", "financing-available"],
    website: "https://www.planetfitness.com/franchising",
  },
  {
    slug: "orangetheory-fitness",
    name: "Orangetheory Fitness",
    category: "Health & Fitness",
    description:
      "Heart-rate-monitored group fitness franchise blending cardio and strength training. Premium pricing and high member engagement drive strong per-unit revenue. Science-backed workout methodology creates sticky membership base.",
    investmentMin: 563_000,
    investmentMax: 1_548_000,
    franchiseFee: 59_950,
    royaltyPct: 8.0,
    adFundPct: 2.0,
    avgRevenue: 1_200_000,
    unitCount: 1_530,
    unitsOpened: 68,
    unitsClosed: 42,
    yearFounded: 2010,
    headquarters: "Boca Raton, FL",
    tags: ["multi-unit", "financing-available"],
    website: "https://www.orangetheory.com/en-us/franchise",
  },
  {
    slug: "the-joint-chiropractic",
    name: "The Joint Chiropractic",
    category: "Health & Fitness",
    description:
      "Walk-in, membership-based chiropractic care with no insurance hassles. Retail-style locations in strip malls make chiropractic accessible and affordable. Recurring revenue model with strong patient retention rates.",
    investmentMin: 264_400,
    investmentMax: 478_900,
    franchiseFee: 39_900,
    royaltyPct: 7.0,
    adFundPct: 2.0,
    avgRevenue: 780_000,
    unitCount: 890,
    unitsOpened: 112,
    unitsClosed: 18,
    yearFounded: 1999,
    headquarters: "Scottsdale, AZ",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://www.thejoint.com/franchise",
  },
  {
    slug: "stretch-zone",
    name: "Stretch Zone",
    category: "Health & Fitness",
    description:
      "Practitioner-assisted stretching concept riding the recovery and wellness trend. Proprietary patented strapping system differentiates from competitors. Membership-based recurring revenue with no expensive equipment requirements.",
    investmentMin: 152_800,
    investmentMax: 330_600,
    franchiseFee: 49_500,
    royaltyPct: 8.0,
    adFundPct: 2.0,
    avgRevenue: 550_000,
    unitCount: 450,
    unitsOpened: 128,
    unitsClosed: 8,
    yearFounded: 2004,
    headquarters: "Boca Raton, FL",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://www.stretchzone.com/franchise",
  },
  {
    slug: "club-pilates",
    name: "Club Pilates",
    category: "Health & Fitness",
    description:
      "Largest Pilates franchise in the world with reformer-based group classes. Xponential Fitness brand with strong unit economics and growing consumer demand. Appeals to a broad demographic from beginners to advanced practitioners.",
    investmentMin: 220_000,
    investmentMax: 475_000,
    franchiseFee: 60_000,
    royaltyPct: 7.0,
    adFundPct: 2.0,
    avgRevenue: 620_000,
    unitCount: 820,
    unitsOpened: 105,
    unitsClosed: 22,
    yearFounded: 2007,
    headquarters: "Irvine, CA",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://www.clubpilates.com/franchise",
  },
  {
    slug: "pure-barre",
    name: "Pure Barre",
    category: "Health & Fitness",
    description:
      "Barre-focused boutique fitness concept with a fiercely loyal female-skewing member base. Low-impact, high-results positioning appeals to wide age range. Xponential Fitness brand with efficient small-footprint studios.",
    investmentMin: 219_000,
    investmentMax: 464_000,
    franchiseFee: 54_500,
    royaltyPct: 7.0,
    adFundPct: 2.0,
    avgRevenue: 420_000,
    unitCount: 680,
    unitsOpened: 42,
    unitsClosed: 28,
    yearFounded: 2001,
    headquarters: "Irvine, CA",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://www.purebarre.com/franchise",
  },
  {
    slug: "snap-fitness",
    name: "Snap Fitness",
    category: "Health & Fitness",
    description:
      "Compact 24/7 gym concept with lower buildout costs than full-size fitness centers. Lift Brands portfolio company offering flexible floorplans for various market sizes. Strong international presence alongside US growth.",
    investmentMin: 210_000,
    investmentMax: 530_000,
    franchiseFee: 20_000,
    royaltyPct: 6.0,
    adFundPct: 2.0,
    avgRevenue: 420_000,
    unitCount: 1_200,
    unitsOpened: 52,
    unitsClosed: 64,
    yearFounded: 2003,
    headquarters: "Chanhassen, MN",
    tags: ["semi-absentee", "veteran-discount", "financing-available"],
    website: "https://www.snapfitness.com/us/franchise",
  },

  // ─── Home Services ───────────────────────────────────────────
  {
    slug: "mosquito-joe",
    name: "Mosquito Joe",
    category: "Home Services",
    description:
      "Outdoor pest control franchise specializing in mosquito, tick, and flea treatment. Neighborly brands portfolio company with seasonal but highly profitable operations. Low overhead home-based model with recurring service revenue.",
    investmentMin: 112_500,
    investmentMax: 157_400,
    franchiseFee: 42_500,
    royaltyPct: 7.0,
    adFundPct: 2.0,
    avgRevenue: 530_000,
    unitCount: 440,
    unitsOpened: 55,
    unitsClosed: 18,
    yearFounded: 2012,
    headquarters: "Virginia Beach, VA",
    tags: ["home-based", "semi-absentee", "veteran-discount", "financing-available"],
    website: "https://www.mosquitojoefranchise.com",
  },
  {
    slug: "mosquito-authority",
    name: "Mosquito Authority",
    category: "Home Services",
    description:
      "Mosquito barrier treatment franchise with a simple, repeatable service model. Low-cost entry point and home-based operation make it attractive for first-time business owners. All-natural treatment options differentiate from chemical-heavy competitors.",
    investmentMin: 45_000,
    investmentMax: 95_000,
    franchiseFee: 25_000,
    royaltyPct: 8.0,
    adFundPct: 0.0,
    avgRevenue: 350_000,
    unitCount: 320,
    unitsOpened: 42,
    unitsClosed: 14,
    yearFounded: 2009,
    headquarters: "Mooresville, NC",
    tags: ["home-based", "owner-operator", "veteran-discount"],
    website: "https://www.mosquitoauthority.com/franchise",
  },
  {
    slug: "servpro",
    name: "Servpro",
    category: "Home Services",
    description:
      "Fire and water damage restoration leader with strong insurance company relationships. High-margin emergency services create recession-resistant revenue streams. Extensive training and certification programs for franchisees.",
    investmentMin: 221_000,
    investmentMax: 330_000,
    franchiseFee: 63_500,
    royaltyPct: 8.0,
    adFundPct: 3.0,
    avgRevenue: 1_600_000,
    unitCount: 2_000,
    unitsOpened: 68,
    unitsClosed: 34,
    yearFounded: 1967,
    headquarters: "Gallatin, TN",
    tags: ["multi-unit", "veteran-discount", "financing-available"],
    website: "https://www.servpro.com/franchise",
  },
  {
    slug: "window-genie",
    name: "Window Genie",
    category: "Home Services",
    description:
      "Window cleaning, pressure washing, and tinting franchise in the Neighbourly family of home service brands. Low startup costs and high repeat customer rates drive owner satisfaction. Simple operations with scalable crew-based model.",
    investmentMin: 98_000,
    investmentMax: 175_000,
    franchiseFee: 45_000,
    royaltyPct: 7.0,
    adFundPct: 2.0,
    avgRevenue: 380_000,
    unitCount: 180,
    unitsOpened: 22,
    unitsClosed: 8,
    yearFounded: 1994,
    headquarters: "Ann Arbor, MI",
    tags: ["home-based", "owner-operator", "veteran-discount", "financing-available"],
    website: "https://www.windowgeniefranchise.com",
  },
  {
    slug: "painting-with-a-twist",
    name: "Painting with a Twist",
    category: "Home Services",
    description:
      "Paint-and-sip entertainment franchise offering guided painting classes with BYOB. Fun social atmosphere drives strong word-of-mouth and corporate event bookings. Low food cost model with high-margin consumable supplies.",
    investmentMin: 96_000,
    investmentMax: 190_000,
    franchiseFee: 25_000,
    royaltyPct: 6.0,
    adFundPct: 2.0,
    avgRevenue: 420_000,
    unitCount: 330,
    unitsOpened: 18,
    unitsClosed: 24,
    yearFounded: 2009,
    headquarters: "Mandeville, LA",
    tags: ["semi-absentee", "financing-available"],
    website: "https://paintingwithatwist.com/franchise",
  },

  // ─── Education ───────────────────────────────────────────────
  {
    slug: "kumon",
    name: "Kumon",
    category: "Education",
    description:
      "World's largest after-school math and reading enrichment program with a self-learning worksheet methodology. Proven 60-year track record across 60+ countries. Low-tech, high-touch model that parents trust for academic advancement.",
    investmentMin: 67_500,
    investmentMax: 145_400,
    franchiseFee: 2_000,
    royaltyPct: 0.0,
    adFundPct: 0.0,
    avgRevenue: 480_000,
    unitCount: 25_600,
    unitsOpened: 85,
    unitsClosed: 125,
    yearFounded: 1954,
    headquarters: "Teaneck, NJ",
    tags: ["owner-operator"],
    website: "https://www.kumon.com/franchise",
  },
  {
    slug: "mathnasium",
    name: "Mathnasium",
    category: "Education",
    description:
      "Math-only tutoring center franchise using proprietary Mathnasium Method for K-12 students. After-school and weekend hours allow for semi-absentee ownership. Strong parent demand driven by math anxiety and standardized test preparation.",
    investmentMin: 112_000,
    investmentMax: 148_000,
    franchiseFee: 49_000,
    royaltyPct: 10.0,
    adFundPct: 3.0,
    avgRevenue: 370_000,
    unitCount: 1_130,
    unitsOpened: 92,
    unitsClosed: 48,
    yearFounded: 2002,
    headquarters: "Los Angeles, CA",
    tags: ["semi-absentee", "owner-operator", "financing-available"],
    website: "https://www.mathnasium.com/franchise",
  },
  {
    slug: "huntington-learning",
    name: "Huntington Learning Centers",
    category: "Education",
    description:
      "Comprehensive tutoring and test prep franchise serving K-12 students for over 45 years. SAT/ACT prep services command premium pricing. Proven diagnostic assessment approach differentiates from tutoring marketplaces.",
    investmentMin: 168_000,
    investmentMax: 283_000,
    franchiseFee: 36_000,
    royaltyPct: 8.0,
    adFundPct: 2.0,
    avgRevenue: 510_000,
    unitCount: 310,
    unitsOpened: 22,
    unitsClosed: 12,
    yearFounded: 1977,
    headquarters: "Oradell, NJ",
    tags: ["owner-operator", "veteran-discount", "financing-available"],
    website: "https://huntingtonfranchise.com",
  },
  {
    slug: "sylvan-learning",
    name: "Sylvan Learning",
    category: "Education",
    description:
      "Established supplemental education brand offering personalized tutoring and STEM programs. Hybrid in-center and online model provides scheduling flexibility for families. Strong brand recognition among parents of school-age children.",
    investmentMin: 86_000,
    investmentMax: 199_000,
    franchiseFee: 24_000,
    royaltyPct: 9.0,
    adFundPct: 1.5,
    avgRevenue: 440_000,
    unitCount: 540,
    unitsOpened: 18,
    unitsClosed: 24,
    yearFounded: 1979,
    headquarters: "Baltimore, MD",
    tags: ["semi-absentee", "financing-available"],
    website: "https://franchise.sylvanlearning.com",
  },
  {
    slug: "kiddie-academy",
    name: "Kiddie Academy",
    category: "Education",
    description:
      "Full-service childcare and early education franchise serving children ages six weeks to 12 years. Proprietary Life Essentials curriculum goes beyond academics to build character. High-revenue model with strong community demand for quality childcare.",
    investmentMin: 460_000,
    investmentMax: 1_080_000,
    franchiseFee: 140_000,
    royaltyPct: 7.0,
    adFundPct: 2.5,
    avgRevenue: 2_200_000,
    unitCount: 330,
    unitsOpened: 35,
    unitsClosed: 4,
    yearFounded: 1981,
    headquarters: "Abingdon, MD",
    tags: ["semi-absentee", "financing-available"],
    website: "https://kiddieacademy.com/franchising",
  },
  {
    slug: "goddard-school",
    name: "The Goddard School",
    category: "Education",
    description:
      "Premium early childhood education franchise with play-based STEAM curriculum. Consistently ranked as a top childcare franchise with waitlists at most locations. High-revenue model requires significant upfront investment but delivers strong returns.",
    investmentMin: 710_000,
    investmentMax: 1_070_000,
    franchiseFee: 150_000,
    royaltyPct: 7.0,
    adFundPct: 3.0,
    avgRevenue: 2_800_000,
    unitCount: 620,
    unitsOpened: 42,
    unitsClosed: 2,
    yearFounded: 1988,
    headquarters: "King of Prussia, PA",
    tags: ["semi-absentee", "financing-available"],
    website: "https://www.goddardschool.com/franchise",
  },

  // ─── Pet Services ────────────────────────────────────────────
  {
    slug: "camp-bow-wow",
    name: "Camp Bow Wow",
    category: "Pet Services",
    description:
      "Premier doggy daycare and boarding franchise with live web cameras parents love. Growing pet humanization trend drives consistent demand for premium pet care. Multi-revenue-stream model includes daycare, boarding, grooming, and training.",
    investmentMin: 1_057_000,
    investmentMax: 1_787_000,
    franchiseFee: 50_000,
    royaltyPct: 7.0,
    adFundPct: 2.0,
    avgRevenue: 1_200_000,
    unitCount: 210,
    unitsOpened: 18,
    unitsClosed: 6,
    yearFounded: 2000,
    headquarters: "Westminster, CO",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://www.campbowwow.com/franchise",
  },

  // ─── B2B Services ────────────────────────────────────────────
  {
    slug: "fastsigns",
    name: "FASTSIGNS",
    category: "B2B Services",
    description:
      "Leading signage and visual communications franchise serving businesses of all sizes. Wide product range from banners to digital displays creates diverse revenue streams. Propelled Brands parent company and strong B2B recurring relationships.",
    investmentMin: 233_000,
    investmentMax: 307_000,
    franchiseFee: 49_750,
    royaltyPct: 6.0,
    adFundPct: 2.0,
    avgRevenue: 910_000,
    unitCount: 770,
    unitsOpened: 28,
    unitsClosed: 12,
    yearFounded: 1985,
    headquarters: "Carrollton, TX",
    tags: ["veteran-discount", "financing-available", "owner-operator"],
    website: "https://www.fastsigns.com/franchise-opportunity",
  },
  {
    slug: "the-ups-store",
    name: "The UPS Store",
    category: "B2B Services",
    description:
      "Largest franchisor in the shipping, postal, printing, and business services category. Built-in brand recognition through UPS parent company drives foot traffic. Small-business-focused model with multiple revenue streams from packaging to notary services.",
    investmentMin: 177_000,
    investmentMax: 403_000,
    franchiseFee: 29_950,
    royaltyPct: 5.0,
    adFundPct: 2.5,
    avgRevenue: 620_000,
    unitCount: 5_500,
    unitsOpened: 78,
    unitsClosed: 92,
    yearFounded: 1980,
    headquarters: "San Diego, CA",
    tags: ["owner-operator", "veteran-discount", "financing-available"],
    website: "https://www.theupsstorefranchise.com",
  },
  {
    slug: "brightway-insurance",
    name: "Brightway Insurance",
    category: "B2B Services",
    description:
      "Multi-carrier insurance distribution franchise offering home, auto, and commercial lines. Franchisees access dozens of carriers without building those relationships independently. Recurring commission income creates long-term wealth-building opportunity.",
    investmentMin: 95_000,
    investmentMax: 180_000,
    franchiseFee: 30_000,
    royaltyPct: 0.0,
    adFundPct: 0.0,
    avgRevenue: 620_000,
    unitCount: 350,
    unitsOpened: 45,
    unitsClosed: 12,
    yearFounded: 2003,
    headquarters: "Jacksonville, FL",
    tags: ["home-based", "semi-absentee", "financing-available"],
    website: "https://brightway.com/franchise",
  },
  {
    slug: "supergreen-solutions",
    name: "SuperGreen Solutions",
    category: "B2B Services",
    description:
      "Energy efficiency and sustainability consulting franchise helping businesses reduce utility costs. Growing ESG and sustainability mandates drive corporate demand. Low overhead model with high-value B2B contracts and recurring audit revenue.",
    investmentMin: 75_000,
    investmentMax: 180_000,
    franchiseFee: 39_500,
    royaltyPct: 5.0,
    adFundPct: 1.0,
    avgRevenue: null,
    unitCount: 48,
    unitsOpened: 8,
    unitsClosed: 4,
    yearFounded: 2009,
    headquarters: "St. Petersburg, FL",
    tags: ["home-based", "semi-absentee"],
    website: "https://supergreensolutions.com/franchise",
  },

  // ─── Personal Care ───────────────────────────────────────────
  {
    slug: "sport-clips",
    name: "Sport Clips",
    category: "Personal Care",
    description:
      "Sports-themed men's and boys' hair salon franchise with the MVP Experience. Walk-in model with no appointments necessary drives high throughput. Strong military community involvement and veteran franchisee recruitment.",
    investmentMin: 266_000,
    investmentMax: 439_000,
    franchiseFee: 25_000,
    royaltyPct: 6.0,
    adFundPct: 5.0,
    avgRevenue: 520_000,
    unitCount: 1_850,
    unitsOpened: 55,
    unitsClosed: 42,
    yearFounded: 1993,
    headquarters: "Georgetown, TX",
    tags: ["semi-absentee", "multi-unit", "veteran-discount", "financing-available"],
    website: "https://www.sportclips.com/franchise",
  },
  {
    slug: "great-clips",
    name: "Great Clips",
    category: "Personal Care",
    description:
      "Largest hair salon franchise in North America with industry-leading technology including online check-in. No-appointment, value-priced model with recession-resistant demand. Strong multi-unit ownership culture with experienced franchisee base.",
    investmentMin: 183_000,
    investmentMax: 397_000,
    franchiseFee: 20_000,
    royaltyPct: 6.0,
    adFundPct: 5.0,
    avgRevenue: 550_000,
    unitCount: 4_500,
    unitsOpened: 95,
    unitsClosed: 72,
    yearFounded: 1982,
    headquarters: "Minneapolis, MN",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://www.greatclipsfranchise.com",
  },
  {
    slug: "supercuts",
    name: "Supercuts",
    category: "Personal Care",
    description:
      "Well-known value hair salon brand under the Regis Corporation umbrella. Walk-in friendly model with consistent pricing and reliable service. Strong name recognition drives steady foot traffic in strip center locations.",
    investmentMin: 148_000,
    investmentMax: 306_000,
    franchiseFee: 22_500,
    royaltyPct: 6.0,
    adFundPct: 5.0,
    avgRevenue: 380_000,
    unitCount: 2_100,
    unitsOpened: 22,
    unitsClosed: 88,
    yearFounded: 1975,
    headquarters: "Minneapolis, MN",
    tags: ["semi-absentee", "multi-unit"],
    website: "https://www.supercuts.com/franchise",
  },
  {
    slug: "massage-envy",
    name: "Massage Envy",
    category: "Personal Care",
    description:
      "Largest provider of therapeutic massage and skin care in the US with membership-based recurring revenue. Strong brand awareness drives member acquisition. Total body care positioning with massage, stretch, and facial services.",
    investmentMin: 487_000,
    investmentMax: 1_012_000,
    franchiseFee: 60_000,
    royaltyPct: 6.0,
    adFundPct: 2.0,
    avgRevenue: 1_100_000,
    unitCount: 1_160,
    unitsOpened: 18,
    unitsClosed: 34,
    yearFounded: 2002,
    headquarters: "Scottsdale, AZ",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://www.massageenvy.com/franchise",
  },
  {
    slug: "hand-and-stone",
    name: "Hand & Stone Massage and Facial Spa",
    category: "Personal Care",
    description:
      "Membership-based massage and facial spa franchise with professional-grade services at accessible prices. Growing wellness category tailwind with focus on recurring monthly memberships. Clean, upscale spa environment differentiates from independent operators.",
    investmentMin: 554_000,
    investmentMax: 696_000,
    franchiseFee: 50_000,
    royaltyPct: 6.0,
    adFundPct: 2.0,
    avgRevenue: 950_000,
    unitCount: 580,
    unitsOpened: 48,
    unitsClosed: 14,
    yearFounded: 2004,
    headquarters: "Trevose, PA",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://www.handandstonefranchise.com",
  },
  {
    slug: "european-wax-center",
    name: "European Wax Center",
    category: "Personal Care",
    description:
      "Leading body waxing franchise with proprietary Comfort Wax technology. Subscription-based wax pass model creates predictable recurring revenue. Strong unit economics and growing consumer preference for professional waxing services.",
    investmentMin: 379_000,
    investmentMax: 607_000,
    franchiseFee: 45_000,
    royaltyPct: 6.0,
    adFundPct: 3.0,
    avgRevenue: 880_000,
    unitCount: 920,
    unitsOpened: 62,
    unitsClosed: 18,
    yearFounded: 2004,
    headquarters: "Plano, TX",
    tags: ["semi-absentee", "multi-unit", "financing-available"],
    website: "https://waxcenter.com/franchise",
  },

  // ─── Automotive ──────────────────────────────────────────────
  {
    slug: "christian-brothers-automotive",
    name: "Christian Brothers Automotive",
    category: "Automotive",
    description:
      "Full-service auto repair franchise with a values-driven culture and transparent pricing. Nice difference guarantee and dealer-level diagnostics build customer trust. Consistently top-ranked in franchisee satisfaction surveys.",
    investmentMin: 521_000,
    investmentMax: 727_000,
    franchiseFee: 95_000,
    royaltyPct: 4.0,
    adFundPct: 2.0,
    avgRevenue: 2_100_000,
    unitCount: 290,
    unitsOpened: 42,
    unitsClosed: 2,
    yearFounded: 1982,
    headquarters: "Houston, TX",
    tags: ["owner-operator", "financing-available"],
    website: "https://www.cbac.com/franchise",
  },
  {
    slug: "meineke",
    name: "Meineke Car Care Centers",
    category: "Automotive",
    description:
      "Established auto repair and maintenance franchise with over 50 years of brand recognition. Driven Brands portfolio company with fleet services adding B2B revenue. Comprehensive services from oil changes to major repairs.",
    investmentMin: 267_000,
    investmentMax: 565_000,
    franchiseFee: 35_000,
    royaltyPct: 7.0,
    adFundPct: 8.0,
    avgRevenue: 1_050_000,
    unitCount: 720,
    unitsOpened: 22,
    unitsClosed: 35,
    yearFounded: 1972,
    headquarters: "Charlotte, NC",
    tags: ["multi-unit", "veteran-discount", "financing-available"],
    website: "https://meinekefranchise.com",
  },
  {
    slug: "aamco",
    name: "AAMCO Transmissions",
    category: "Automotive",
    description:
      "Iconic transmission and total car care brand with the strongest name in drivetrain repair. Expanding beyond transmission specialization into complete auto service. Driven Brands portfolio company with strong national advertising presence.",
    investmentMin: 227_000,
    investmentMax: 333_000,
    franchiseFee: 39_500,
    royaltyPct: 7.0,
    adFundPct: 6.0,
    avgRevenue: 950_000,
    unitCount: 550,
    unitsOpened: 12,
    unitsClosed: 22,
    yearFounded: 1963,
    headquarters: "Charlotte, NC",
    tags: ["owner-operator", "veteran-discount", "financing-available"],
    website: "https://www.aamcofranchises.com",
  },

  // ─── Senior Care ─────────────────────────────────────────────
  {
    slug: "visiting-angels",
    name: "Visiting Angels",
    category: "Senior Care",
    description:
      "Largest non-medical home care franchise in the US providing companionship and personal care. Aging population demographic tailwind creates decades-long growth runway. Home-based office model with caregiver workforce as primary operating cost.",
    investmentMin: 84_000,
    investmentMax: 125_000,
    franchiseFee: 43_000,
    royaltyPct: 3.5,
    adFundPct: 0.0,
    avgRevenue: 1_500_000,
    unitCount: 680,
    unitsOpened: 32,
    unitsClosed: 18,
    yearFounded: 1998,
    headquarters: "Bryn Mawr, PA",
    tags: ["home-based", "owner-operator", "financing-available"],
    website: "https://www.visitingangels.com/franchise",
  },
  {
    slug: "home-instead",
    name: "Home Instead",
    category: "Senior Care",
    description:
      "Global in-home senior care leader with over 1,200 locations worldwide. Comprehensive caregiver training program and proprietary care assessment tools. Strong brand reputation with families seeking quality care for aging parents.",
    investmentMin: 115_000,
    investmentMax: 145_000,
    franchiseFee: 55_000,
    royaltyPct: 5.0,
    adFundPct: 1.0,
    avgRevenue: 1_800_000,
    unitCount: 1_200,
    unitsOpened: 28,
    unitsClosed: 14,
    yearFounded: 1994,
    headquarters: "Omaha, NE",
    tags: ["home-based", "owner-operator", "veteran-discount", "financing-available"],
    website: "https://www.homeinstead.com/franchise",
  },
  {
    slug: "right-at-home",
    name: "Right at Home",
    category: "Senior Care",
    description:
      "In-home care and assistance franchise offering both personal care and skilled nursing services. National accounts with insurance providers create referral pipelines. Strong training and support system for healthcare-sector newcomers.",
    investmentMin: 89_000,
    investmentMax: 149_000,
    franchiseFee: 49_500,
    royaltyPct: 5.0,
    adFundPct: 1.5,
    avgRevenue: 1_600_000,
    unitCount: 720,
    unitsOpened: 38,
    unitsClosed: 16,
    yearFounded: 1995,
    headquarters: "Omaha, NE",
    tags: ["home-based", "owner-operator", "veteran-discount", "financing-available"],
    website: "https://www.rightathome.com/franchise",
  },
  {
    slug: "comfort-keepers",
    name: "Comfort Keepers",
    category: "Senior Care",
    description:
      "In-home care franchise emphasizing interactive caregiving to keep seniors engaged and active. Sodexo subsidiary with strong corporate backing and resources. Proprietary Interactive Caregiving approach differentiates from competitors.",
    investmentMin: 94_000,
    investmentMax: 160_000,
    franchiseFee: 45_000,
    royaltyPct: 5.0,
    adFundPct: 2.0,
    avgRevenue: 1_300_000,
    unitCount: 600,
    unitsOpened: 18,
    unitsClosed: 22,
    yearFounded: 1998,
    headquarters: "Irvine, CA",
    tags: ["home-based", "owner-operator", "financing-available"],
    website: "https://comfortkeepersfranchise.com",
  },
  {
    slug: "interim-healthcare",
    name: "Interim HealthCare",
    category: "Senior Care",
    description:
      "One of the oldest home health, hospice, and staffing franchises in the United States. Medical and non-medical service lines create diversified revenue. Caring Brands International portfolio company with strong institutional relationships.",
    investmentMin: 150_000,
    investmentMax: 350_000,
    franchiseFee: 55_000,
    royaltyPct: 5.5,
    adFundPct: 1.0,
    avgRevenue: 3_200_000,
    unitCount: 580,
    unitsOpened: 22,
    unitsClosed: 14,
    yearFounded: 1966,
    headquarters: "Sunrise, FL",
    tags: ["owner-operator", "veteran-discount", "financing-available"],
    website: "https://www.interimhealthcare.com/franchise",
  },

  // ─── Cleaning & Maintenance ──────────────────────────────────
  {
    slug: "jan-pro",
    name: "Jan-Pro",
    category: "Cleaning & Maintenance",
    description:
      "Commercial cleaning franchise with a master franchise model that provides guaranteed initial customer base. EnviroShield disinfection system became a major differentiator during and after the pandemic. Low entry cost makes it accessible for first-time entrepreneurs.",
    investmentMin: 4_170,
    investmentMax: 56_000,
    franchiseFee: 3_000,
    royaltyPct: 8.0,
    adFundPct: 0.0,
    avgRevenue: 120_000,
    unitCount: 8_500,
    unitsOpened: 650,
    unitsClosed: 480,
    yearFounded: 1991,
    headquarters: "Alpharetta, GA",
    tags: ["owner-operator", "veteran-discount"],
    website: "https://jan-pro.com/franchise",
  },
  {
    slug: "jani-king",
    name: "Jani-King",
    category: "Cleaning & Maintenance",
    description:
      "World's largest commercial cleaning franchise with operations in over 10 countries. Provides initial customer contracts to help franchisees ramp quickly. Comprehensive training and regional support infrastructure.",
    investmentMin: 3_900,
    investmentMax: 56_000,
    franchiseFee: 3_400,
    royaltyPct: 10.0,
    adFundPct: 0.0,
    avgRevenue: 110_000,
    unitCount: 7_200,
    unitsOpened: 520,
    unitsClosed: 410,
    yearFounded: 1969,
    headquarters: "Dallas, TX",
    tags: ["owner-operator", "veteran-discount", "financing-available"],
    website: "https://www.janiking.com/franchise",
  },
  {
    slug: "servicemaster-clean",
    name: "ServiceMaster Clean",
    category: "Cleaning & Maintenance",
    description:
      "Legacy commercial and residential cleaning brand with decades of brand equity. Part of the ServiceMaster portfolio alongside Terminix and Merry Maids. Diverse service offerings from janitorial to disaster restoration create multiple revenue streams.",
    investmentMin: 90_000,
    investmentMax: 210_000,
    franchiseFee: 36_000,
    royaltyPct: 7.0,
    adFundPct: 1.0,
    avgRevenue: 620_000,
    unitCount: 3_200,
    unitsOpened: 65,
    unitsClosed: 88,
    yearFounded: 1929,
    headquarters: "Memphis, TN",
    tags: ["multi-unit", "veteran-discount", "financing-available"],
    website: "https://www.ownafranchise.com/servicemaster-clean",
  },
  {
    slug: "merry-maids",
    name: "Merry Maids",
    category: "Cleaning & Maintenance",
    description:
      "Leading residential cleaning franchise with over 40 years of operational refinement. ServiceMaster brands subsidiary with strong national brand awareness. Proven systems for hiring, training, and retaining cleaning teams at scale.",
    investmentMin: 94_000,
    investmentMax: 161_000,
    franchiseFee: 37_500,
    royaltyPct: 7.0,
    adFundPct: 2.0,
    avgRevenue: 550_000,
    unitCount: 1_400,
    unitsOpened: 32,
    unitsClosed: 48,
    yearFounded: 1979,
    headquarters: "Memphis, TN",
    tags: ["owner-operator", "financing-available"],
    website: "https://www.merrymaids.com/franchise",
  },
  {
    slug: "molly-maid",
    name: "Molly Maid",
    category: "Cleaning & Maintenance",
    description:
      "Residential cleaning franchise within the Neighborly family of home service brands. Strong brand trust built over 40 years of consistent service. Cross-marketing opportunities with other Neighborly brands drive customer acquisition.",
    investmentMin: 115_000,
    investmentMax: 170_000,
    franchiseFee: 14_900,
    royaltyPct: 6.5,
    adFundPct: 2.0,
    avgRevenue: 620_000,
    unitCount: 470,
    unitsOpened: 22,
    unitsClosed: 18,
    yearFounded: 1984,
    headquarters: "Waco, TX",
    tags: ["owner-operator", "veteran-discount", "financing-available"],
    website: "https://www.mollymaid.com/franchise",
  },
  {
    slug: "two-maids",
    name: "Two Maids",
    category: "Cleaning & Maintenance",
    description:
      "Residential cleaning franchise with a unique pay-for-performance compensation model for cleaners. Higher customer satisfaction drives better cleaner pay, aligning incentives throughout the system. Acquired by Home Franchise Concepts, fueling accelerated growth.",
    investmentMin: 80_000,
    investmentMax: 145_000,
    franchiseFee: 45_000,
    royaltyPct: 6.0,
    adFundPct: 2.0,
    avgRevenue: 580_000,
    unitCount: 140,
    unitsOpened: 28,
    unitsClosed: 6,
    yearFounded: 2003,
    headquarters: "Birmingham, AL",
    tags: ["owner-operator", "financing-available"],
    website: "https://twomaidsfranchise.com",
  },
  {
    slug: "maidpro",
    name: "MaidPro",
    category: "Cleaning & Maintenance",
    description:
      "Tech-forward residential cleaning franchise with proprietary software platform for scheduling and operations. Home Franchise Concepts portfolio company with strong unit economics. Modern brand positioning appeals to digitally savvy homeowners.",
    investmentMin: 74_000,
    investmentMax: 190_000,
    franchiseFee: 15_000,
    royaltyPct: 6.0,
    adFundPct: 2.0,
    avgRevenue: 510_000,
    unitCount: 260,
    unitsOpened: 18,
    unitsClosed: 12,
    yearFounded: 1991,
    headquarters: "Boston, MA",
    tags: ["owner-operator", "home-based", "financing-available"],
    website: "https://www.maidprofranchise.com",
  },

  // ─── Real Estate ─────────────────────────────────────────────
  {
    slug: "remax",
    name: "RE/MAX",
    category: "Real Estate",
    description:
      "Global real estate brokerage franchise with the highest agent productivity in the industry. Agent-centric commission model attracts top-producing agents. Iconic balloon brand and 'Above the Crowd' positioning are universally recognized.",
    investmentMin: 38_000,
    investmentMax: 227_000,
    franchiseFee: 25_000,
    royaltyPct: 0.0,
    adFundPct: 0.0,
    avgRevenue: null,
    unitCount: 9_000,
    unitsOpened: 185,
    unitsClosed: 210,
    yearFounded: 1973,
    headquarters: "Denver, CO",
    tags: ["semi-absentee", "owner-operator"],
    website: "https://www.remax.com/franchise",
  },
  {
    slug: "keller-williams",
    name: "Keller Williams Realty",
    category: "Real Estate",
    description:
      "Largest real estate franchise by agent count with a unique profit-sharing model. Agent-owned, technology-driven culture with KW Command platform. Training-focused organization known for producing top real estate professionals.",
    investmentMin: 183_000,
    investmentMax: 337_000,
    franchiseFee: 35_000,
    royaltyPct: 6.0,
    adFundPct: 0.0,
    avgRevenue: null,
    unitCount: 1_100,
    unitsOpened: 42,
    unitsClosed: 28,
    yearFounded: 1983,
    headquarters: "Austin, TX",
    tags: ["owner-operator"],
    website: "https://www.kw.com/franchise",
  },

  // ─── Retail ──────────────────────────────────────────────────
  {
    slug: "ace-hardware",
    name: "Ace Hardware",
    category: "Retail",
    description:
      "Cooperative-model hardware retailer where franchisees own the store and share in wholesale buying power. Local neighborhood positioning differentiates from big-box competitors. Helpful hardware folks branding drives strong customer loyalty.",
    investmentMin: 300_000,
    investmentMax: 2_000_000,
    franchiseFee: 5_000,
    royaltyPct: 0.0,
    adFundPct: 0.0,
    avgRevenue: 2_500_000,
    unitCount: 5_700,
    unitsOpened: 145,
    unitsClosed: 88,
    yearFounded: 1924,
    headquarters: "Oak Brook, IL",
    tags: ["owner-operator", "financing-available"],
    website: "https://www.acehardware.com/franchise",
  },
  {
    slug: "batteries-plus",
    name: "Batteries Plus",
    category: "Retail",
    description:
      "Specialty retailer and service provider for batteries, light bulbs, and device repair. Unique niche positioning with limited direct competition. Device repair services add high-margin revenue stream beyond product sales.",
    investmentMin: 249_000,
    investmentMax: 484_000,
    franchiseFee: 37_500,
    royaltyPct: 5.0,
    adFundPct: 2.0,
    avgRevenue: 950_000,
    unitCount: 700,
    unitsOpened: 28,
    unitsClosed: 18,
    yearFounded: 1988,
    headquarters: "Hartland, WI",
    tags: ["semi-absentee", "multi-unit", "veteran-discount", "financing-available"],
    website: "https://www.batteriesplusfranchise.com",
  },
  {
    slug: "brightspring-health",
    name: "BrightSpring Health Services",
    category: "Senior Care",
    description:
      "Diversified home and community-based health services provider offering pharmacy, home health, and rehabilitation. Broad service portfolio addresses multiple points in the senior care continuum. Growing demand from aging demographics and hospital-to-home care transitions.",
    investmentMin: 120_000,
    investmentMax: 280_000,
    franchiseFee: 50_000,
    royaltyPct: 5.0,
    adFundPct: 1.0,
    avgRevenue: 2_400_000,
    unitCount: 380,
    unitsOpened: 24,
    unitsClosed: 10,
    yearFounded: 2019,
    headquarters: "Louisville, KY",
    tags: ["owner-operator", "financing-available"],
    website: "https://www.brightspringhealth.com",
  },
];
